// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Js_undefined from "rescript/lib/es6/js_undefined.js";

function test(v1, v2, parser) {
  console.log(parser);
  return Curry._3(parser, [{
                v1: v1,
                v2: v2
              }], Caml_option.some(Js_undefined.fromOption("world!")), Caml_option.some(Js_undefined.fromOption(1)));
}

export {
  test ,
  
}
/* No side effect */
